# Generated by Django 6.0.7 on 2026-07-14 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('date_earned', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-date_earned'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated technologies and tools.', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='code', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='CollinsTechEmpire', max_length=100)),
                ('availability_status', models.CharField(default='Available for engineering, AI, software, research, and digital projects', max_length=220)),
                ('hero_headline', models.CharField(default='Electrical Engineer, AI Professional, Python & Django Developer, and Renewable Energy Specialist', max_length=255)),
                ('hero_intro', models.TextField(default='I combine engineering, artificial intelligence, software development, renewable energy, research, and digital creativity to build practical solutions for businesses, communities, and society.')),
                ('supporting_text', models.TextField(default='Through CollinsTechEmpire, I develop intelligent digital products, engineering systems, renewable-energy solutions, technical content, and innovative technology-driven projects.')),
                ('footer_statement', models.TextField(default='CollinsTechEmpire combines engineering, artificial intelligence, software development, renewable energy, research, and digital creativity to build practical solutions for a changing world.')),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=80)),
                ('url', models.URLField()),
                ('icon_name', models.CharField(default='external', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='ToolkitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('icon_name', models.CharField(default='code', max_length=30)),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='Technology', max_length=80),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_covers/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Optional short summary for article cards.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='enquiry_type',
            field=models.CharField(blank=True, choices=[('engineering', 'Engineering consultation'), ('solar', 'Solar and electrical services'), ('django', 'Django development'), ('ai', 'AI collaboration'), ('research', 'Research and writing'), ('creative', 'Design and digital content'), ('general', 'General enquiry')], max_length=30),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, choices=[('ai', 'Artificial Intelligence'), ('software', 'Software Development'), ('engineering', 'Engineering'), ('energy', 'Renewable Energy'), ('research', 'Research & Communication'), ('creative', 'Digital Creativity'), ('operations', 'Professional Operations')], max_length=30),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_name',
            field=models.CharField(blank=True, default='code', max_length=30),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='Engr. Josiah Collins Chinaza', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='long_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Engr. Josiah Collins Chinaza', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional. Leave blank rather than using an estimated percentage.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='professional_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
