# Generated by Django 6.0.7 on 2026-07-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_seed_alx_certifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('graphic_design', 'Graphic Design'), ('video', 'Video & Motion'), ('branding', 'Branding'), ('web', 'Web & UI Design'), ('engineering', 'Engineering Work'), ('photography', 'Photography'), ('other', 'Other Creative Work')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(help_text='Upload the finished design or a clear screenshot/thumbnail of the work.', upload_to='work_samples/')),
                ('client_or_company', models.CharField(blank=True, max_length=160)),
                ('project_date', models.DateField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, help_text='Optional link to YouTube, Vimeo, Google Drive, or another video page.')),
                ('external_url', models.URLField(blank=True, help_text='Optional project or campaign link.')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-project_date', '-created_at'],
            },
        ),
    ]
