# Generated by Django 6.0.7 on 2026-07-15 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_worksample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('organization_type', models.CharField(choices=[('employer', 'Employer'), ('enterprise', 'Enterprise'), ('platform', 'Media or digital platform'), ('practice', 'Independent practice')], max_length=20)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('website_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='certification',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Select only when supporting evidence or a verification link is available.'),
        ),
        migrations.AddField(
            model_name='certification',
            name='record_type',
            field=models.CharField(choices=[('certificate', 'Certificate'), ('qualification', 'Educational qualification'), ('training', 'Professional training'), ('seminar', 'Seminar')], default='certificate', max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='period_label',
            field=models.CharField(blank=True, help_text='Use when the exact starting date is unknown, for example "Present".', max_length=80),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(help_text='Organisation name shown when no Organisation record is selected.', max_length=180),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_roles', to='main.organization'),
        ),
    ]
