# Generated by Django 6.0.7 on 2026-07-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_seed_professional_journey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['order', '-date_earned'], 'verbose_name': 'credential', 'verbose_name_plural': 'credentials'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-is_current', 'order', '-start_date'], 'verbose_name': 'professional role', 'verbose_name_plural': 'professional roles'},
        ),
    ]
