# Generated by Django 6.0.7 on 2026-07-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_certification_options_alter_experience_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background_watermark',
            field=models.ImageField(blank=True, help_text='Optional faint image shown across the public website. Upload a logo or professional portrait; the CollinsTechEmpire logo is used when left blank.', null=True, upload_to='site_branding/'),
        ),
    ]
