# Generated by Django 6.0.7 on 2026-07-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_blogcomment_blogreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='device_brand',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
